### PR TITLE
Fix type of StaticDocumentSpec.document in index.d.ts

### LINKED ISSUE #327: Wrong Type for StaticDocumentSpec.document in index.d.ts
Code checks for an object
https://github.com/fastify/fastify-swagger/blob/6799cd424dfb02211e514c7b5257e5c57cea04ab/static.js#L54

but it is defined as a string. 
https://github.com/fastify/fastify-swagger/blob/6799cd424dfb02211e514c7b5257e5c57cea04ab/index.d.ts#L71

### PR DESCRIPTION
**Pull request by radzom**
Closes #327

The type of the property 'document' in the interface StaticDocumentSpec in the file 'index.d.ts' was formerly specified as 'string' and was corrected to object.

I think one could even specify it as one of
 - SwaggerSchema.Spec (for swagger V2 specs -already imported) or
 - OpenApi3Spec (for OpenApi V3 specs - where can this come from?)

Are there other versions that would then need to be supported?

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

File: index.d.ts [hunk 1]
```diff
@@ -68,12 +68,12 @@ export interface StaticPathSpec {
 }
 
 export interface StaticDocumentSpec {
-  document: string;
+  document: SwaggerSchema.Spec | object;
```
Comment (fox1t) [inline index.d.ts:71]: Why also including `object` here?

Comment (radzom) [reply index.d.ts:71]: Because otherwise OpenAPI3 specs would not be allowed. I am happy to integrate

Comment (radzom) [reply index.d.ts:71]: So object is a catch all safety feedback in lack of knowing what specs have to be supported.
Just SwaggerSchema.Spec is not enough since it will only allow V2 Specs.
Hope i could make my point clear.

Comment (Ethan-Arrowood) [reply index.d.ts:71]: Would rather us `Record<string, unknown>` instead of `object`. 

But also I don't see why we shouldn't use their official types package

Comment (radzom) [reply index.d.ts:71]: So, which option is prefered?
A) change object to Record<string, unknown>
or
B) import types from "openapi-types"

I was not aware of that these types were official. Knowing that i strongly tend to option B.

File: examples/example-static-specification.json [hunk 2]
```diff
@@ -8,10 +8,12 @@
       "email": "super.developer@gmail.com"
     }
   },
-  "servers": {
-    "url": "http://localhost:3000/",
-    "description": "Localhost (uses test data)"
-  },
+  "servers": [
```
Comment (radzom) [inline examples/example-static-specification.json:11]: This was an error found because of the new spec.

File: package.json [hunk 3]
```diff
@@ -48,7 +48,8 @@
     "fastify-plugin": "^3.0.0",
     "fastify-static": "^3.3.0",
     "js-yaml": "^3.14.0",
-    "json-schema-resolver": "^1.2.0"
+    "json-schema-resolver": "^1.2.0",
+    "openapi-types": "^7.0.1"
```
Comment (radzom) [inline package.json:52]: added new package with ^ as all the other packages. (seems to be the prefered way here)

File: tsconfig.json [hunk 4]
```diff
@@ -0,0 +1,9 @@
+{
```
Comment (radzom) [inline tsconfig.json:1]: I had to turn on the --resolveJsonModule switch for importing json files.
I first looked for commandline options in "tsd --help" but there are none.

File: package.json (hunk 3 above)
Comment (mcollina) [reply package.json:52]: I would not recommend adding this dependency, maybe as a devDep?

File: tsconfig.json [hunk 5]
```diff
@@ -0,0 +1,9 @@
...
+  "compilerOptions": {
+    "target": "es2015",
+    "module": "commonjs",
+    "strict": true,
+    "moduleResolution": "node",
+    "resolveJsonModule": true
```
Comment (mcollina) [inline tsconfig.json:7]: This requires adding some new settings to TS for using this lib, and I think it should be avoided.

**Review by mcollina — CHANGES_REQUESTED** [review]

File: tsconfig.json (hunk 5 above)
Comment (radzom) [reply tsconfig.json]: I can avoid this, by importing a minimal openapiv3 spec from a .ts file instead of a .json file.

File: package.json (hunk 3 above)
Comment (radzom) [reply package.json]: good finding, already corrected

File: index.d.ts (hunk 1 above)
Comment (fox1t) [reply index.d.ts]: I prefer `openapi-types` path too. This plung supports only version 2, though. Are we introducing incompatibilities/breaking changes? If so I would go with `Record<string, unknown>`  for the moment.

**Review by fox1t — APPROVED** [review]

**Review by Ethan-Arrowood — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by radzom** [comment]
Hi, is there anything left I need, can or have to do for this pull request?
I am not impatient, just curious.
It is my first PR, so i am not sure if the Checklist needs to be checked and wo does it. 
My assumption was someone else :-).

**Comment by Ethan-Arrowood** [comment]
@radzom nothing else on your end I believe. We do our merges and releases manually so whenever that happens for this plugin your work will be completed and released. Thank you for contributing 😄

**Comment by climba03003** [comment]
@mcollina Sorry for tagging you. I do not know who is responsible for this plugin but I can see that there are no more change needed in here and with 3 persons approval. Should this PR be landed? I need the typing for #333.

**Comment by mcollina** [comment]
Landed :)
