### PR TITLE
Fix: redirect to index

### LINKED ISSUE #65: Wrong redirect
The redirection should be made with an absolute url and redirect to `/documentation/index.html`

https://github.com/fastify/fastify-swagger/blob/master/routes.js#L10

### PR DESCRIPTION
**Pull request by allevo**
Fix #65

### CODE REVIEW

File: routes.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ function fastifySwagger (fastify, opts, next) {
     url: '/',
     method: 'GET',
     schema: { hide: true },
-    handler: (request, reply) => reply.redirect(`.${opts.prefix}/`)
+    handler: (request, reply) => reply.redirect(`${opts.prefix}/index.html`)
```
Comment (mcollina) [inline routes.js]: I don't think that `opts.prefix` here is correct. Can you add a test that loads this within another plugin, so that this is exposed as `/v1/documentation`? I think it should use [`fastify.basePath`](https://github.com/fastify/fastify/blob/master/docs/Server-Methods.md#basepath).

Comment (allevo) [reply routes.js]: nice catch!! fixed

**Comment by mcollina** [comment]
Feel free to release it to land and release it to npm as minor!

**Comment by allevo** [comment]
@mcollina I have no right to merge this PR

**Comment by mcollina** [comment]
Now you can :D
